// client/components/SearchBar/index.vue
<template>
  <div
    class="w-[16rem] h-[2rem] bg-slate-100 p-2 gap-2 relative border border-neutral-200 rounded-md"
  >
    <input
      class="w-[90%] bg-transparent h-full flex outline-none"
      placeholder="Search"
    />
    <Icon
      name="lucide:search"
      class="absolute right-2 top-1/2 -translate-y-1/2"
    />
  </div>
</template>

<script lang="ts" setup></script>

// client/src/components/Navbar/Search/SearchBar.tsx
import { Search01Icon } from "hugeicons-react";

const SearchBar = () => {
  return (
    <div className="relative flex p-2 gap-2">
      <input
        className="w-full border border-solid border-borderColor p-2 shadow-sm rounded-md outline-primary"
        placeholder="Search"
      />
      <Search01Icon className="absolute top-1/2 -translate-y-1/2 right-4" />
    </div>
  );
};

export default SearchBar;
