// client/components/UI/Button.vue
<template>
  <button :class="button({ variant })">
    <slot />
  </button>
</template>

<script lang="ts" setup>
import { cva, type VariantProps } from "class-variance-authority";

const { variant } = defineProps(["variant"]);

const button = cva(["p-2 font-semibold rounded-md"], {
  variants: {
    variant: {
      primary: "bg-primary text-white",
      outline: "bg-white text-primary border-2 border-primary",
    },
  },
});
</script>

// client/src/components/UI/Button.tsx
import {cva, type VariantProps} from 'class-variance-authority'
import React, {ButtonHTMLAttributes} from "react";
import {twMerge} from "tailwind-merge";


const button = cva(['shadow-sm rounded-sm'],{
    variants: {
        variant: {
            primary: 'bg-primary text-white',
        }
    }
});

type Props = {
    children?: React.ReactNode,
    className?: string;
} & VariantProps<typeof button> & ButtonHTMLAttributes<HTMLButtonElement>;

const Button = ({children,variant,className,...props} : Props) => {
    return (
        <button {...props}  className={twMerge(className,button({variant}))}>{children}</button>
    )
}

export default Button;
